### ISSUE TITLE
RqFormBallot.java:41: Add unit tests for this method.

### ISSUE THREAD

**Issue by 0pdd** [condorcat/de.serra.condorcat#48]
The puzzle `46-77382f25` from #46 has to be resolved: 

https://github.com/Serranya/de.serra.condorcat/blob/bd593d168f449d8fd118b8698a55da12c53de178/src/main/java/de/serra/condorcat/ballot/RqFormBallot.java#L41-L41

The puzzle was created by @Serranya on 10-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@serranya please pay attention to this new issue.

**Comment by Serranya** [comment]
Old puzzle
