### ISSUE TITLE
SimpleLanguages.java:12: These list should be generated...

### ISSUE THREAD

**Issue by 0pdd** [condorcat/de.serra.condorcat#88]
The puzzle `86-a6d7494b` from #86 has to be resolved: 

https://github.com/Serranya/de.serra.condorcat/blob/04a9354973ae869d2092769c9d6f77152445e48f/src/main/java/de/serra/condorcat/i18n/SimpleLanguages.java#L12-L12

The puzzle was created by @Serranya on 14-Aug-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@serranya please pay attention to this new issue.

**Comment by Serranya** [comment]
Old puzzle
